issues:
  exclude-dirs:
  - temp

linters:
  enable-all: true
  disable:
  - tagliatelle
  - varnamelen
  - depguard
  - godox
  - execinquery
  - gomnd
  - goimports # conflicts with gofumpt
  - gci       # conflicts with gofumpt
  - gofumpt   # broken, just run task fmt

linters-settings:
  ireturn:
    allow:
    - error
    - stdlib
    - generic

  wrapcheck:
    ignoreSigs:
    - errors.New(
    - errorx.Decorate(
    - status.Error(
    - status.Errorf(
    - fmt.Errorf(
